#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-profvis
Version  : 0.3.8
Release  : 8
URL      : https://cran.r-project.org/src/contrib/profvis_0.3.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/profvis_0.3.8.tar.gz
Summary  : Interactive Visualizations for Profiling R Code
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 MIT
Requires: R-profvis-lib = %{version}-%{release}
Requires: R-profvis-license = %{version}-%{release}
Requires: R-htmlwidgets
Requires: R-purrr
Requires: R-rlang
Requires: R-stringr
Requires: R-vctrs
BuildRequires : R-htmlwidgets
BuildRequires : R-purrr
BuildRequires : R-rlang
BuildRequires : R-stringr
BuildRequires : R-vctrs
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Profvis
=======
<!-- badges: start -->
[![R-CMD-check](https://github.com/rstudio/profvis/workflows/R-CMD-check/badge.svg)](https://github.com/rstudio/profvis/actions)
<!-- badges: end -->

%package lib
Summary: lib components for the R-profvis package.
Group: Libraries
Requires: R-profvis-license = %{version}-%{release}

%description lib
lib components for the R-profvis package.


%package license
Summary: license components for the R-profvis package.
Group: Default

%description license
license components for the R-profvis package.


%prep
%setup -q -n profvis

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683147909

%install
export SOURCE_DATE_EPOCH=1683147909
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-profvis
cp %{_builddir}/profvis/LICENSE %{buildroot}/usr/share/package-licenses/R-profvis/006554fd5c6da3395fee406b5bc4d8d16643077f || :
cp %{_builddir}/profvis/inst/htmlwidgets/lib/d3/LICENSE %{buildroot}/usr/share/package-licenses/R-profvis/2c753d952d9009aafb9460d5d1edbb24617d30c6 || :
cp %{_builddir}/profvis/inst/htmlwidgets/lib/highlight/LICENSE %{buildroot}/usr/share/package-licenses/R-profvis/cd25196630fe891662ad77810f0f6dee5bc85ddc || :
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/profvis/DESCRIPTION
/usr/lib64/R/library/profvis/INDEX
/usr/lib64/R/library/profvis/LICENSE
/usr/lib64/R/library/profvis/Meta/Rd.rds
/usr/lib64/R/library/profvis/Meta/features.rds
/usr/lib64/R/library/profvis/Meta/hsearch.rds
/usr/lib64/R/library/profvis/Meta/links.rds
/usr/lib64/R/library/profvis/Meta/nsInfo.rds
/usr/lib64/R/library/profvis/Meta/package.rds
/usr/lib64/R/library/profvis/NAMESPACE
/usr/lib64/R/library/profvis/NEWS.md
/usr/lib64/R/library/profvis/R/profvis
/usr/lib64/R/library/profvis/R/profvis.rdb
/usr/lib64/R/library/profvis/R/profvis.rdx
/usr/lib64/R/library/profvis/help/AnIndex
/usr/lib64/R/library/profvis/help/aliases.rds
/usr/lib64/R/library/profvis/help/paths.rds
/usr/lib64/R/library/profvis/help/profvis.rdb
/usr/lib64/R/library/profvis/help/profvis.rdx
/usr/lib64/R/library/profvis/html/00Index.html
/usr/lib64/R/library/profvis/html/R.css
/usr/lib64/R/library/profvis/htmlwidgets/lib/d3/LICENSE
/usr/lib64/R/library/profvis/htmlwidgets/lib/d3/d3.min.js
/usr/lib64/R/library/profvis/htmlwidgets/lib/highlight/LICENSE
/usr/lib64/R/library/profvis/htmlwidgets/lib/highlight/default.css
/usr/lib64/R/library/profvis/htmlwidgets/lib/highlight/highlight.js
/usr/lib64/R/library/profvis/htmlwidgets/lib/highlight/textmate.css
/usr/lib64/R/library/profvis/htmlwidgets/lib/jquery/jquery.min.js
/usr/lib64/R/library/profvis/htmlwidgets/lib/profvis/profvis.css
/usr/lib64/R/library/profvis/htmlwidgets/lib/profvis/profvis.js
/usr/lib64/R/library/profvis/htmlwidgets/lib/profvis/scroll.js
/usr/lib64/R/library/profvis/htmlwidgets/profvis.js
/usr/lib64/R/library/profvis/htmlwidgets/profvis.yaml
/usr/lib64/R/library/profvis/shinymodule/draggable-helper.js
/usr/lib64/R/library/profvis/tests/manual-test-source.R
/usr/lib64/R/library/profvis/tests/manual-tests.R
/usr/lib64/R/library/profvis/tests/test-all.R
/usr/lib64/R/library/profvis/tests/testthat/_snaps/rprof.md
/usr/lib64/R/library/profvis/tests/testthat/helper-profvis.R
/usr/lib64/R/library/profvis/tests/testthat/test-parse-sort1.R
/usr/lib64/R/library/profvis/tests/testthat/test-parse.R
/usr/lib64/R/library/profvis/tests/testthat/test-parse.prof
/usr/lib64/R/library/profvis/tests/testthat/test-profvis.R
/usr/lib64/R/library/profvis/tests/testthat/test-rprof.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/profvis/libs/profvis.so
/usr/lib64/R/library/profvis/libs/profvis.so.avx2
/usr/lib64/R/library/profvis/libs/profvis.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-profvis/006554fd5c6da3395fee406b5bc4d8d16643077f
/usr/share/package-licenses/R-profvis/2c753d952d9009aafb9460d5d1edbb24617d30c6
/usr/share/package-licenses/R-profvis/cd25196630fe891662ad77810f0f6dee5bc85ddc
