#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-profvis
Version  : 0.4.0
Release  : 10
URL      : https://cran.r-project.org/src/contrib/profvis_0.4.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/profvis_0.4.0.tar.gz
Summary  : Interactive Visualizations for Profiling R Code
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: R-profvis-lib = %{version}-%{release}
Requires: R-profvis-license = %{version}-%{release}
Requires: R-htmlwidgets
Requires: R-rlang
Requires: R-vctrs
BuildRequires : R-htmlwidgets
BuildRequires : R-rlang
BuildRequires : R-vctrs
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
profvis
=======
<!-- badges: start -->
[![R-CMD-check](https://github.com/r-lib/profvis/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/r-lib/profvis/actions/workflows/R-CMD-check.yaml)
[![Codecov test coverage](https://codecov.io/gh/r-lib/profvis/graph/badge.svg)](https://app.codecov.io/gh/r-lib/profvis)
<!-- badges: end -->

%package lib
Summary: lib components for the R-profvis package.
Group: Libraries
Requires: R-profvis-license = %{version}-%{release}

%description lib
lib components for the R-profvis package.


%package license
Summary: license components for the R-profvis package.
Group: Default

%description license
license components for the R-profvis package.


%prep
%setup -q -n profvis
pushd ..
cp -a profvis buildavx2
popd
pushd ..
cp -a profvis buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726842781

%install
export SOURCE_DATE_EPOCH=1726842781
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-profvis
cp %{_builddir}/profvis/inst/htmlwidgets/lib/d3/LICENSE %{buildroot}/usr/share/package-licenses/R-profvis/2c753d952d9009aafb9460d5d1edbb24617d30c6 || :
cp %{_builddir}/profvis/inst/htmlwidgets/lib/highlight/LICENSE %{buildroot}/usr/share/package-licenses/R-profvis/cd25196630fe891662ad77810f0f6dee5bc85ddc || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/profvis/DESCRIPTION
/usr/lib64/R/library/profvis/INDEX
/usr/lib64/R/library/profvis/LICENSE
/usr/lib64/R/library/profvis/Meta/Rd.rds
/usr/lib64/R/library/profvis/Meta/features.rds
/usr/lib64/R/library/profvis/Meta/hsearch.rds
/usr/lib64/R/library/profvis/Meta/links.rds
/usr/lib64/R/library/profvis/Meta/nsInfo.rds
/usr/lib64/R/library/profvis/Meta/package.rds
/usr/lib64/R/library/profvis/Meta/vignette.rds
/usr/lib64/R/library/profvis/NAMESPACE
/usr/lib64/R/library/profvis/NEWS.md
/usr/lib64/R/library/profvis/R/profvis
/usr/lib64/R/library/profvis/R/profvis.rdb
/usr/lib64/R/library/profvis/R/profvis.rdx
/usr/lib64/R/library/profvis/doc/index.html
/usr/lib64/R/library/profvis/doc/profvis.R
/usr/lib64/R/library/profvis/doc/profvis.Rmd
/usr/lib64/R/library/profvis/doc/profvis.html
/usr/lib64/R/library/profvis/help/AnIndex
/usr/lib64/R/library/profvis/help/aliases.rds
/usr/lib64/R/library/profvis/help/paths.rds
/usr/lib64/R/library/profvis/help/profvis.rdb
/usr/lib64/R/library/profvis/help/profvis.rdx
/usr/lib64/R/library/profvis/html/00Index.html
/usr/lib64/R/library/profvis/html/R.css
/usr/lib64/R/library/profvis/htmlwidgets/lib/d3/LICENSE
/usr/lib64/R/library/profvis/htmlwidgets/lib/d3/d3.min.js
/usr/lib64/R/library/profvis/htmlwidgets/lib/highlight/LICENSE
/usr/lib64/R/library/profvis/htmlwidgets/lib/highlight/highlight.min.js
/usr/lib64/R/library/profvis/htmlwidgets/lib/highlight/textmate.css
/usr/lib64/R/library/profvis/htmlwidgets/lib/jquery/AUTHORS.txt
/usr/lib64/R/library/profvis/htmlwidgets/lib/jquery/jquery.min.js
/usr/lib64/R/library/profvis/htmlwidgets/lib/profvis/profvis.css
/usr/lib64/R/library/profvis/htmlwidgets/lib/profvis/profvis.js
/usr/lib64/R/library/profvis/htmlwidgets/lib/profvis/scroll.js
/usr/lib64/R/library/profvis/htmlwidgets/profvis.js
/usr/lib64/R/library/profvis/htmlwidgets/profvis.yaml
/usr/lib64/R/library/profvis/shinymodule/draggable-helper.js
/usr/lib64/R/library/profvis/tests/test-all.R
/usr/lib64/R/library/profvis/tests/testthat/_snaps/pause.md
/usr/lib64/R/library/profvis/tests/testthat/_snaps/profvis.md
/usr/lib64/R/library/profvis/tests/testthat/helper-profvis.R
/usr/lib64/R/library/profvis/tests/testthat/test-parse-sort1.R
/usr/lib64/R/library/profvis/tests/testthat/test-parse.R
/usr/lib64/R/library/profvis/tests/testthat/test-parse.prof
/usr/lib64/R/library/profvis/tests/testthat/test-pause.R
/usr/lib64/R/library/profvis/tests/testthat/test-profvis.R
/usr/lib64/R/library/profvis/tests/testthat/test-utils.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/profvis/libs/profvis.so
/V4/usr/lib64/R/library/profvis/libs/profvis.so
/usr/lib64/R/library/profvis/libs/profvis.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-profvis/2c753d952d9009aafb9460d5d1edbb24617d30c6
/usr/share/package-licenses/R-profvis/cd25196630fe891662ad77810f0f6dee5bc85ddc
